baseURL = 'https://scr.qu.edu.iq/'
locale = 'ar'
defaultContentLanguage = 'ar'
defaultContentLanguageInSubdir = true
title = "قسم البعثات والعلاقات الثقافية - جامعة القادسية"
buildFuture = true

[Params]
  cms_repo = "qaduni/scr.qu.edu.iq"
  cms_branch = "main"

[module]
  [[module.imports]]
      path = "github.com/qaduni/qu.theme"

[pagination]
  pagerSize = 10

[languages]
  [languages.ar]
    label = "العربية"
    weight = 1
    direction = "rtl"
    locale = "ar"

  [languages.en]
    label = "English"
    weight = 2
    direction = "ltr"
    locale = "en"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

[mediaTypes."application/manifest+json"]
  suffixes = ["webmanifest"]

[outputFormats.WebManifest]
  mediaType = "application/manifest+json"
  baseName = "manifest"
  isPlainText = true
  notAlternative = true

[mediaTypes."text/yaml"]
  suffixes = ["yaml"]

[outputFormats.ConfigYML]
  mediaType = "text/yaml"
  baseName = "config"
  isPlainText = true
  notAlternative = true
  path = "admin"
  root = true

[mediaTypes."text/llm"]
  suffixes = ["txt"]

[outputFormats.LLM]
  mediaType = "text/llm"
  baseName = "llms"
  isPlainText = true
  notAlternative = true

[outputs]
  home = ["HTML", "RSS", "WebManifest", "ConfigYML", "Robots", "LLM"]