# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: qaduni/scr.qu.edu.iq
  branch: main
  auth_methods:
    - token

media_folder: "static/media"
public_folder: "/media"

i18n:
  structure: multiple_files
  locales:
    - ar
    - en
  default_locale: ar
  omit_default_locale_from_file_path: true

media_libraries:
  all:
    max_file_size: 5120000
    slugify_filename: true
    transformations:
      raster_image:
        format: webp
        quality: 85
      svg:
        optimize: true

site_url: https://qa.qu.edu.iq
display_url: https://qa.qu.edu.iq

collections:
  - name: "news"
    label: "الأخبار"
    label_singular: "خبر"
    description: "الاخبار تظهر في الصفحة الرئيسية ومركز الاخبار وتحتوي على غلاف."
    i18n: true
    folder: "content/media/news"
    path: "{{year}}/{{month}}/{{day}}/{{slug}}"
    preview_path: "media/news/{{year}}/{{month}}/{{day}}/{{slug}}"
    slug: "{{uuid_shorter}}"
    create: true
    sortable_fields:
      - "date"
      - "title"
    media_folder: "/static/media"
    public_folder: "/media"
    fields:
      - label: "العنوان"
        name: "title"
        widget: "string"
        required: true
        i18n: true
        pattern: &title_pattern
          - "^[a-zA-Z0-9\\u0600-\\u06FF\\s-]{10,75}$"
          - "يجب أن يكون الوصف بين 10 و 75 حرفًا."
      - label: "الوصف"
        name: "description"
        widget: "text"
        required: true
        i18n: true
        pattern: &description_pattern
          - "^[a-zA-Z0-9\\u0600-\\u06FF\\s-]{30,120}$"
          - "يجب أن يكون الوصف بين 30 و 120 حرفًا."
      - label: "الصورة"
        name: "image"
        widget: "image"
        required: false
        i18n: duplicate
      - label: "المحتوى"
        name: "body"
        widget: "markdown"
        i18n: true
      - label: "التاريخ"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
        time_format: false
        default: "{{now}}"
        required: true
        i18n: duplicate

  - name: "announcements"
    label: "الإعلانات"
    label_singular: "إعلان"
    description: "الإعلانات تظهر في الصفحة الرئيسية ومركز الاخبار ولا تحتوي على غلاف."
    i18n: true
    folder: "content/media/announcements"
    path: "{{year}}/{{month}}/{{day}}/{{slug}}"
    slug: "{{uuid_shorter}}"
    create: true
    sortable_fields:
      - "date"
      - "title"
    media_folder: "/static/media"
    public_folder: "/media"
    fields:
      - label: "العنوان"
        name: "title"
        widget: "string"
        required: true
        i18n: true
        pattern: *title_pattern
      - label: "هل الاعلان مهم؟"
        name: "important"
        widget: "boolean"
        default: false
        i18n: duplicate
      - label: "الوصف"
        name: "description"
        widget: "text"
        required: true
        i18n: true
        pattern: *description_pattern
      - label: "المحتوى"
        name: "body"
        widget: "markdown"
        i18n: true
      - label: "التاريخ"
        name: "date"
        widget: "datetime"
        format: "YYYY-MM-DD"
        date_format: "YYYY-MM-DD"
        time_format: false
        default: "{{now}}"
        required: true
        i18n: duplicate

  - name: "about_pages"
    label: "حول"
    folder: "content/about"
    create: false
    i18n: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    fields: &default_fields
      - label: "Title"
        name: "title"
        widget: "string"
        i18n: true
      - label: "Description"
        name: "description"
        widget: "string"
        required: true
        i18n: true
      - label: "Body"
        name: "body"
        widget: "markdown"
        i18n: true

  - name: "policies"
    label: "السياسات"
    folder: "content/policies"
    create: false
    i18n: true
    extension: "md"
    format: "frontmatter"
    slug: "{{slug}}"
    fields: *default_fields
